sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE_MS_DOCKER=ap5327/msdocker:1.0.1
  - DOCKER_IMAGE_MS_USERS==ap5327/msusers:1.0.0

script:
  - ./travis.sh
