apiVersion: v1
kind: Service
metadata:
  name: msdocker-service
  labels:
    app: msdocker
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: msdocker
    tier: frontend
