apiVersion: v1
kind: ReplicationController
metadata:
  name: msdocker-rc
  labels:
    app: msdocker
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: msdocker
        tier: frontend
    spec:
      containers:
      - name: msdocker-restapi
        image: ap5327/msdocker:1.0-SNAPSHOT
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
