
kumuluzee:
  logs:
    config-file:
      '<?xml version="1.0" encoding="UTF-8"?>
        <Configuration name="msdocker">
          <Appenders>
            <Console name="console" target="SYSTEM_OUT">
              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
            </Console>
            <Socket name="logstash" host="4e5b9128-db69-46f2-b931-6669acb368d6-ls.logit.io" port="21588" protocol="tcp">
              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
            </Socket>
          </Appenders>
          <Loggers>
            <Root level="all">
              <AppenderRef ref="console" level="info"/>
              <AppenderRef ref="logstash" level="trace"/>
            </Root>
          </Loggers>
        </Configuration>'